# stages:
#   - validate

# validate_branch_name:
#   stage: validate
#   script:
#     - |
#       if [[ ! "$CI_COMMIT_REF_NAME" =~ ^/(Feature|Fix)/ ]]; then
#         echo "Invalid branch name. Please name your branch starting with '/Feature/' or '/Fix/'."
#         exit 1
#       fi
#   only:
#     - branches